
// !! this file is automatically generated; do not modify.

package org.knime.core.table.virtual.expression;

import org.rekex.parser.PegParser;
import org.rekex.parser.ParseResult;

import java.util.List;
import org.knime.core.table.virtual.expression.ExpressionGrammar.Atom;
import org.knime.core.table.virtual.expression.ExpressionGrammar.CtorCatalog;
import org.knime.core.table.virtual.expression.ExpressionGrammar.Expr;
import org.knime.core.table.virtual.expression.ExpressionGrammar.Factor;
import org.knime.core.table.virtual.expression.ExpressionGrammar.OptWs;
import org.knime.core.table.virtual.expression.ExpressionGrammar.StrConst;
import org.knime.core.table.virtual.expression.ExpressionGrammar.Sum;
import org.knime.core.table.virtual.expression.ExpressionGrammar.Term;
import org.rekex.helper.datatype.SepBy1;
import org.rekex.helper.datatype.seq.Seq2;


// Generated recursive descent PEG parser by Rekex

// rootType: Expr

// !! this file is automatically generated; do not modify.
@SuppressWarnings({"all", "unchecked"})
public class ExpressionParser implements PegParser<Expr>
{
    static final int rootTypeRuleId = 0;

    final CtorCatalog catalog;
    public ExpressionParser(CtorCatalog catalog)
    {
        this.catalog = catalog;
    }

    @Override
    public ParseResult<Expr> parse(CharSequence chars, int start, int end)
    {
        _State state = new _State();
        state.catalog = this.catalog;
        state.chars = chars;
        state.start = start;
        state.end = end;
        state.inputInfo = new org.rekex.parser.InputInfo(chars, start, end);

        try
        {
            state = match(rootTypeRuleId, state, -1);
        }
        catch (_FatalEx fatalEx)
        {
            var stack = pathToStack(state.path, state.pathLen);
            return new ParseResult.Fatal<>(fatalEx.position, fatalEx.cause, stack);
        }

        if(!state.fail)
        {
            Expr obj = state.pickObj();
            if(state.start==state.end)
                return new ParseResult.Full<>(obj);
            else
                return new ParseResult.Partial<>(obj, state.start);
        }
        else
        {
            var stack = pathToStack(state.maxFailPath, state.maxFailPath.length);
            String msg = failMsg(state.maxFailReason, state.maxFailEx, _DatatypeList.list.get(state.maxFailRuleId));
            return new ParseResult.Fail<>(state.maxFailPos, msg, state.maxFailEx, stack);
        }
    }

    final static class _State implements Cloneable
    {
        CtorCatalog catalog;
        CharSequence chars;
        int start;
        int end;

        org.rekex.parser.InputInfo inputInfo;

        boolean fail;
        // if fail==false, match is success, obj is set (null is allowed)
        Object obj;

        int[] path = new int[64];
        int pathLen = 0;

        int maxFailPos = -1;
        int[] maxFailPath;
        int maxFailReason;
        Exception maxFailEx;
        int maxFailRuleId;

        public _State clone()
        {
            try {
                return (_State)super.clone();
            } catch (CloneNotSupportedException e) {
                throw new AssertionError(e);
            }
        }

        int gStart, gEnd; // tmp data buffer for regex

        void pathPush(int ruleId, int subIndex)
        {
            if(pathLen+3 > path.length)
                path = java.util.Arrays.copyOf(path, path.length+64);
            path[pathLen++] = ruleId;
            path[pathLen++] = this.start;
            path[pathLen++] = subIndex;
        }
        void pathPop()
        {
            pathLen -= 3;
        }

        _State ok(Object obj)
        {
            this.fail = false;
            this.obj = obj;
            return this;
        }
        <T> T pickObj()
        {
            T t = (T)obj;
            obj = null;
            return t;
        }

        _State fail(int position, int reason, Exception ex, int ruleId, int startReset)
        {
            if(position>maxFailPos)
            {
                maxFailPos = position;
                maxFailPath = java.util.Arrays.copyOf(path, pathLen);
                maxFailReason = reason;
                maxFailEx = ex;
                maxFailRuleId = ruleId;
            }
            return fail(startReset);
        }
        _State fail(int startReset)
        {
            this.fail = true;
            this.obj = null;
            this.start = startReset;
            return this;
        }

    }
    static final int failReason_predicate = 0;   // info: Exception
    static final int failReason_neg = 1;         // info: subrule ID
    static final int failReason_regex = 2;
    static final int failReason_regex_group = 3;

    static String failMsg(int reason, Exception ex, org.rekex.annotype.AnnoType type)
    {
        String typeStr = type.toString(false);
        return switch (reason){
            case failReason_predicate
                -> ex.getMessage()!=null ? ex.getMessage() : ex.toString();
            case failReason_neg
                -> typeStr + " failed; input matched subrule";
            case failReason_regex
                -> "Input does not match regex: "+typeStr;
            case failReason_regex_group
                -> "Input does not match regex group: "+typeStr;
            default -> throw new AssertionError("unexpected reason: "+reason);
        };
    }

    static java.util.ArrayList<ParseResult.Node> pathToStack(int[] path, int pathLen)
    {
        java.util.ArrayList<ParseResult.Node> stack = new java.util.ArrayList<>(pathLen/2);
        for(int i=pathLen-1; i>=0;)
        {
            int _subIndex = path[i--];
            int _start = path[i--];
            int _ruleId = path[i--];
            var datatype = _DatatypeList.list.get(_ruleId);
            stack.add(new ParseResult.Node(datatype, _start, _subIndex));
        }
        return stack;
    }

    static class _FatalEx extends Exception
    {
        final int position;
        final Exception cause;
        _FatalEx(int position, Exception cause)
        {
            super(null, null, false, false);
            this.position = position;
            this.cause = cause;
        }
    }

    // = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
    // rules
    // = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

    static _State match(int ruleId, _State state, int subIndex) throws _FatalEx
    {
        state.pathPush(ruleId, subIndex);
        state = switch(ruleId){
            case 0 -> rule_0(state); // Expr
            case 1 -> rule_1(state); // Sum
            case 2 -> rule_2(state); // SepBy1<Term,@Ch("+-")String>
            case 3 -> rule_3(state); // Term
            case 4 -> rule_4(state); // List<Seq2<@Ch("+-")String,Term>>
            case 5 -> rule_5(state); // SepBy1<Factor,@Ch("*/%")String>
            case 6 -> rule_6(state); // Seq2<@Ch("+-")String,Term>
            case 7 -> rule_7(state); // Factor
            case 8 -> rule_8(state); // List<Seq2<@Ch("*/%")String,Factor>>
            case 9 -> rule_9(state); // @Ch("+-")String
            case 10 -> rule_10(state); // Factor
            case 11 -> rule_11(state); // Factor
            case 12 -> rule_12(state); // Seq2<@Ch("*/%")String,Factor>
            case 13 -> rule_13(state); // OptWs
            case 14 -> rule_14(state); // Atom
            case 15 -> rule_15(state); // @Ch("*/%")String
            case 16 -> rule_16(state); // Atom
            case 17 -> rule_17(state); // Atom
            case 18 -> rule_18(state); // Atom
            case 19 -> rule_19(state); // Atom
            case 20 -> rule_20(state); // Atom
            case 21 -> rule_21(state); // Atom
            case 22 -> rule_22(state); // @Ch("$")Void
            case 23 -> rule_23(state); // @Ch("[")Void
            case 24 -> rule_24(state); // StrConst
            case 25 -> rule_25(state); // @Ch("]")Void
            case 26 -> rule_26(state); // @Regex("[0-9]+")String
            case 27 -> rule_27(state); // @Ch(except="\\\" \t\n\r+-*/%",range={32,1114111})int[]
            case 28 -> rule_28(state); // @Ch("(")Void
            case 29 -> rule_29(state); // @Ch(")")Void
            case 30 -> rule_30(state); // @Ch("\"")Void
            case 31 -> rule_31(state); // int[]
            case 32 -> rule_32(state); // @Ch(except="\\\" \t\n\r+-*/%",range={32,1114111})int
            case 33 -> rule_33(state); // int
            case 34 -> rule_34(state); // int
            case 35 -> rule_35(state); // int
            case 36 -> rule_36(state); // int
            case 37 -> rule_37(state); // @Ch(except="\\\"",range={32,1114111})int
            case 38 -> rule_38(state); // @Ch("\\")Void
            case 39 -> rule_39(state); // @Ch("\\\"/bfnrt")char
            case 40 -> rule_40(state); // @Ch("u")Void
            case 41 -> rule_41(state); // byte
            case 42 -> rule_42(state); // @Regex("[0-9A-Fa-f]")char
            default -> throw new AssertionError("unknown ruleId: "+ruleId);
        };
        state.pathPop();
        return state;
    }

    // concat rule for: Expr
    static _State rule_0(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(1, state, 0); // arg_0: Sum
        if(state.fail)
            return state.fail(start0);
        Sum arg_0 = state.pickObj();

        Expr value;
        try{
            value = state.catalog.expr(arg_0);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // concat rule for: Sum
    static _State rule_1(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(2, state, 0); // arg_0: SepBy1<Term,@Ch("+-")String>
        if(state.fail)
            return state.fail(start0);
        SepBy1<Term, String> arg_0 = state.pickObj();

        Sum value;
        try{
            value = state.catalog.sum(arg_0);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // concat rule for: SepBy1<Term,@Ch("+-")String>
    static _State rule_2(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(3, state, 0); // arg_0: Term
        if(state.fail)
            return state.fail(start0);
        Term arg_0 = state.pickObj();

        state = match(4, state, 1); // arg_1: List<Seq2<@Ch("+-")String,Term>>
        if(state.fail)
            return state.fail(start0);
        List<Seq2<String, Term>> arg_1 = state.pickObj();

        SepBy1<Term, String> value;
        try{
            value = SepBy1.ctor(arg_0, arg_1);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // concat rule for: Term
    static _State rule_3(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(5, state, 0); // arg_0: SepBy1<Factor,@Ch("*/%")String>
        if(state.fail)
            return state.fail(start0);
        SepBy1<Factor, String> arg_0 = state.pickObj();

        Term value;
        try{
            value = state.catalog.term(arg_0);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // repeat rule for: List<Seq2<@Ch("+-")String,Term>>
    static _State rule_4(_State state) throws _FatalEx
    {
        state = match_repeat(state, 4, 6, 0, Integer.MAX_VALUE);
        if(state.fail)
            return state;
        java.util.ArrayList<Seq2<String, Term>> list = state.pickObj();
        list.trimToSize();
        return state.ok(list);
    }

    // concat rule for: SepBy1<Factor,@Ch("*/%")String>
    static _State rule_5(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(7, state, 0); // arg_0: Factor
        if(state.fail)
            return state.fail(start0);
        Factor arg_0 = state.pickObj();

        state = match(8, state, 1); // arg_1: List<Seq2<@Ch("*/%")String,Factor>>
        if(state.fail)
            return state.fail(start0);
        List<Seq2<String, Factor>> arg_1 = state.pickObj();

        SepBy1<Factor, String> value;
        try{
            value = SepBy1.ctor(arg_0, arg_1);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // concat rule for: Seq2<@Ch("+-")String,Term>
    static _State rule_6(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(9, state, 0); // arg_0: @Ch("+-")String
        if(state.fail)
            return state.fail(start0);
        String arg_0 = state.pickObj();

        state = match(3, state, 1); // arg_1: Term
        if(state.fail)
            return state.fail(start0);
        Term arg_1 = state.pickObj();

        Seq2<String, Term> value;
        try{
            value = new Seq2<String, Term>(arg_0, arg_1);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // alt rule for: Factor
    static _State rule_7(_State state) throws _FatalEx
    {
        state = match(10, state, 0); // Factor
        if(!state.fail)
            return state;

        state = match(11, state, 1); // Factor
        if(!state.fail)
            return state;

        return state;
    }


    // repeat rule for: List<Seq2<@Ch("*/%")String,Factor>>
    static _State rule_8(_State state) throws _FatalEx
    {
        state = match_repeat(state, 8, 12, 0, Integer.MAX_VALUE);
        if(state.fail)
            return state;
        java.util.ArrayList<Seq2<String, Factor>> list = state.pickObj();
        list.trimToSize();
        return state.ok(list);
    }

    // regex rule for: @Ch("+-")String
    static _State rule_9(_State state)
    {
        return match_regex_str(state, 9, pattern_9, 0);
    }
    static final java.util.regex.Pattern pattern_9 = java.util.regex.Pattern.compile("[\\+\\-]", 0);

    // concat rule for: Factor
    static _State rule_10(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(13, state, 0); // arg_0: OptWs
        if(state.fail)
            return state.fail(start0);
        OptWs arg_0 = state.pickObj();

        state = match(9, state, 1); // arg_1: @Ch("+-")String
        if(state.fail)
            return state.fail(start0);
        String arg_1 = state.pickObj();

        state = match(7, state, 2); // arg_2: Factor
        if(state.fail)
            return state.fail(start0);
        Factor arg_2 = state.pickObj();

        Factor value;
        try{
            value = state.catalog.factor(arg_0, arg_1, arg_2);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // concat rule for: Factor
    static _State rule_11(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(13, state, 0); // arg_0: OptWs
        if(state.fail)
            return state.fail(start0);
        OptWs arg_0 = state.pickObj();

        state = match(14, state, 1); // arg_1: Atom
        if(state.fail)
            return state.fail(start0);
        Atom arg_1 = state.pickObj();

        Factor value;
        try{
            value = state.catalog.factor(arg_0, arg_1);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // concat rule for: Seq2<@Ch("*/%")String,Factor>
    static _State rule_12(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(15, state, 0); // arg_0: @Ch("*/%")String
        if(state.fail)
            return state.fail(start0);
        String arg_0 = state.pickObj();

        state = match(7, state, 1); // arg_1: Factor
        if(state.fail)
            return state.fail(start0);
        Factor arg_1 = state.pickObj();

        Seq2<String, Factor> value;
        try{
            value = new Seq2<String, Factor>(arg_0, arg_1);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // regex rule for: OptWs
    static _State rule_13(_State state)
    {
        return match_regex_obj(state, 13, pattern_13, 1, OptWs.I);
    }
    static final java.util.regex.Pattern pattern_13 = java.util.regex.Pattern.compile("()[\\ \\t\\n\\r]*", 0);

    // alt rule for: Atom
    static _State rule_14(_State state) throws _FatalEx
    {
        state = match(16, state, 0); // Atom
        if(!state.fail)
            return state;

        state = match(17, state, 1); // Atom
        if(!state.fail)
            return state;

        state = match(18, state, 2); // Atom
        if(!state.fail)
            return state;

        state = match(19, state, 3); // Atom
        if(!state.fail)
            return state;

        state = match(20, state, 4); // Atom
        if(!state.fail)
            return state;

        state = match(21, state, 5); // Atom
        if(!state.fail)
            return state;

        return state;
    }


    // regex rule for: @Ch("*/%")String
    static _State rule_15(_State state)
    {
        return match_regex_str(state, 15, pattern_15, 0);
    }
    static final java.util.regex.Pattern pattern_15 = java.util.regex.Pattern.compile("[\\*/%]", 0);

    // concat rule for: Atom
    static _State rule_16(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(13, state, 0); // arg_0: OptWs
        if(state.fail)
            return state.fail(start0);
        OptWs arg_0 = state.pickObj();

        state = match(22, state, 1); // arg_1: @Ch("$")Void
        if(state.fail)
            return state.fail(start0);
        Void arg_1 = state.pickObj();

        state = match(23, state, 2); // arg_2: @Ch("[")Void
        if(state.fail)
            return state.fail(start0);
        Void arg_2 = state.pickObj();

        state = match(24, state, 3); // arg_3: StrConst
        if(state.fail)
            return state.fail(start0);
        StrConst arg_3 = state.pickObj();

        state = match(25, state, 4); // arg_4: @Ch("]")Void
        if(state.fail)
            return state.fail(start0);
        Void arg_4 = state.pickObj();

        state = match(13, state, 5); // arg_5: OptWs
        if(state.fail)
            return state.fail(start0);
        OptWs arg_5 = state.pickObj();

        Atom value;
        try{
            value = state.catalog.column(arg_0, arg_1, arg_2, arg_3, arg_4, arg_5);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // concat rule for: Atom
    static _State rule_17(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(13, state, 0); // arg_0: OptWs
        if(state.fail)
            return state.fail(start0);
        OptWs arg_0 = state.pickObj();

        state = match(22, state, 1); // arg_1: @Ch("$")Void
        if(state.fail)
            return state.fail(start0);
        Void arg_1 = state.pickObj();

        state = match(23, state, 2); // arg_2: @Ch("[")Void
        if(state.fail)
            return state.fail(start0);
        Void arg_2 = state.pickObj();

        state = match(26, state, 3); // arg_3: @Regex("[0-9]+")String
        if(state.fail)
            return state.fail(start0);
        String arg_3 = state.pickObj();

        state = match(25, state, 4); // arg_4: @Ch("]")Void
        if(state.fail)
            return state.fail(start0);
        Void arg_4 = state.pickObj();

        state = match(13, state, 5); // arg_5: OptWs
        if(state.fail)
            return state.fail(start0);
        OptWs arg_5 = state.pickObj();

        Atom value;
        try{
            value = state.catalog.column(arg_0, arg_1, arg_2, arg_3, arg_4, arg_5);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // concat rule for: Atom
    static _State rule_18(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(13, state, 0); // arg_0: OptWs
        if(state.fail)
            return state.fail(start0);
        OptWs arg_0 = state.pickObj();

        state = match(22, state, 1); // arg_1: @Ch("$")Void
        if(state.fail)
            return state.fail(start0);
        Void arg_1 = state.pickObj();

        state = match(27, state, 2); // arg_2: @Ch(except="\\\" \t\n\r+-*/%",range={32,1114111})int[]
        if(state.fail)
            return state.fail(start0);
        int[] arg_2 = state.pickObj();

        state = match(13, state, 3); // arg_3: OptWs
        if(state.fail)
            return state.fail(start0);
        OptWs arg_3 = state.pickObj();

        Atom value;
        try{
            value = state.catalog.column(arg_0, arg_1, arg_2, arg_3);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // concat rule for: Atom
    static _State rule_19(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(13, state, 0); // arg_0: OptWs
        if(state.fail)
            return state.fail(start0);
        OptWs arg_0 = state.pickObj();

        state = match(28, state, 1); // arg_1: @Ch("(")Void
        if(state.fail)
            return state.fail(start0);
        Void arg_1 = state.pickObj();

        state = match(0, state, 2); // arg_2: Expr
        if(state.fail)
            return state.fail(start0);
        Expr arg_2 = state.pickObj();

        state = match(29, state, 3); // arg_3: @Ch(")")Void
        if(state.fail)
            return state.fail(start0);
        Void arg_3 = state.pickObj();

        state = match(13, state, 4); // arg_4: OptWs
        if(state.fail)
            return state.fail(start0);
        OptWs arg_4 = state.pickObj();

        Atom value;
        try{
            value = state.catalog.group(arg_0, arg_1, arg_2, arg_3, arg_4);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // concat rule for: Atom
    static _State rule_20(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(13, state, 0); // arg_0: OptWs
        if(state.fail)
            return state.fail(start0);
        OptWs arg_0 = state.pickObj();

        state = match(26, state, 1); // arg_1: @Regex("[0-9]+")String
        if(state.fail)
            return state.fail(start0);
        String arg_1 = state.pickObj();

        state = match(13, state, 2); // arg_2: OptWs
        if(state.fail)
            return state.fail(start0);
        OptWs arg_2 = state.pickObj();

        Atom value;
        try{
            value = state.catalog.int_literal(arg_0, arg_1, arg_2);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // concat rule for: Atom
    static _State rule_21(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(24, state, 0); // arg_0: StrConst
        if(state.fail)
            return state.fail(start0);
        StrConst arg_0 = state.pickObj();

        Atom value;
        try{
            value = state.catalog.string_literal(arg_0);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // regex rule for: @Ch("$")Void
    static _State rule_22(_State state)
    {
        return match_regex(state, 22, pattern_22, 0);
    }
    static final java.util.regex.Pattern pattern_22 = java.util.regex.Pattern.compile("\\$", 0);

    // regex rule for: @Ch("[")Void
    static _State rule_23(_State state)
    {
        return match_regex(state, 23, pattern_23, 0);
    }
    static final java.util.regex.Pattern pattern_23 = java.util.regex.Pattern.compile("\\[", 0);

    // concat rule for: StrConst
    static _State rule_24(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(30, state, 0); // arg_0: @Ch("\"")Void
        if(state.fail)
            return state.fail(start0);
        Void arg_0 = state.pickObj();

        state = match(31, state, 1); // arg_1: int[]
        if(state.fail)
            return state.fail(start0);
        int[] arg_1 = state.pickObj();

        state = match(30, state, 2); // arg_2: @Ch("\"")Void
        if(state.fail)
            return state.fail(start0);
        Void arg_2 = state.pickObj();

        state = match(13, state, 3); // arg_3: OptWs
        if(state.fail)
            return state.fail(start0);
        OptWs arg_3 = state.pickObj();

        StrConst value;
        try{
            value = state.catalog.string(arg_0, arg_1, arg_2, arg_3);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // regex rule for: @Ch("]")Void
    static _State rule_25(_State state)
    {
        return match_regex(state, 25, pattern_25, 0);
    }
    static final java.util.regex.Pattern pattern_25 = java.util.regex.Pattern.compile("\\]", 0);

    // regex rule for: @Regex("[0-9]+")String
    static _State rule_26(_State state)
    {
        return match_regex_str(state, 26, pattern_26, 0);
    }
    static final java.util.regex.Pattern pattern_26 = java.util.regex.Pattern.compile("[0-9]+", 0);

    // repeat rule for: @Ch(except="\\\" \t\n\r+-*/%",range={32,1114111})int[]
    static _State rule_27(_State state) throws _FatalEx
    {
        state = match_repeat(state, 27, 32, 0, Integer.MAX_VALUE);
        if(state.fail)
            return state;
        java.util.ArrayList<Integer> list = state.pickObj();
        int[] array = new int[list.size()];
        for(int i=0; i<list.size(); i++)
            array[i] = list.get(i);
        return state.ok(array);
    }

    // regex rule for: @Ch("(")Void
    static _State rule_28(_State state)
    {
        return match_regex(state, 28, pattern_28, 0);
    }
    static final java.util.regex.Pattern pattern_28 = java.util.regex.Pattern.compile("\\(", 0);

    // regex rule for: @Ch(")")Void
    static _State rule_29(_State state)
    {
        return match_regex(state, 29, pattern_29, 0);
    }
    static final java.util.regex.Pattern pattern_29 = java.util.regex.Pattern.compile("\\)", 0);

    // regex rule for: @Ch("\"")Void
    static _State rule_30(_State state)
    {
        return match_regex(state, 30, pattern_30, 0);
    }
    static final java.util.regex.Pattern pattern_30 = java.util.regex.Pattern.compile("\"", 0);

    // repeat rule for: int[]
    static _State rule_31(_State state) throws _FatalEx
    {
        state = match_repeat(state, 31, 33, 0, Integer.MAX_VALUE);
        if(state.fail)
            return state;
        java.util.ArrayList<Integer> list = state.pickObj();
        int[] array = new int[list.size()];
        for(int i=0; i<list.size(); i++)
            array[i] = list.get(i);
        return state.ok(array);
    }

    // regex rule for: @Ch(except="\\\" \t\n\r+-*/%",range={32,1114111})int
    static _State rule_32(_State state) throws _FatalEx
    {
        return match_regex_int(state, 32, pattern_32, 0);
    }
    static final java.util.regex.Pattern pattern_32 = java.util.regex.Pattern.compile("[\\ -\\x{10FFFF}&&[^\\\\\"\\ \\t\\n\\r\\+\\-\\*/%]]", 0);

    // alt rule for: int
    static _State rule_33(_State state) throws _FatalEx
    {
        state = match(34, state, 0); // int
        if(!state.fail)
            return state;

        state = match(35, state, 1); // int
        if(!state.fail)
            return state;

        state = match(36, state, 2); // int
        if(!state.fail)
            return state;

        return state;
    }


    // concat rule for: int
    static _State rule_34(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(37, state, 0); // arg_0: @Ch(except="\\\"",range={32,1114111})int
        if(state.fail)
            return state.fail(start0);
        int arg_0 = state.pickObj();

        int value;
        try{
            value = state.catalog.char1(arg_0);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // concat rule for: int
    static _State rule_35(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(38, state, 0); // arg_0: @Ch("\\")Void
        if(state.fail)
            return state.fail(start0);
        Void arg_0 = state.pickObj();

        state = match(39, state, 1); // arg_1: @Ch("\\\"/bfnrt")char
        if(state.fail)
            return state.fail(start0);
        char arg_1 = state.pickObj();

        int value;
        try{
            value = state.catalog.escC(arg_0, arg_1);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // concat rule for: int
    static _State rule_36(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(38, state, 0); // arg_0: @Ch("\\")Void
        if(state.fail)
            return state.fail(start0);
        Void arg_0 = state.pickObj();

        state = match(40, state, 1); // arg_1: @Ch("u")Void
        if(state.fail)
            return state.fail(start0);
        Void arg_1 = state.pickObj();

        state = match(41, state, 2); // arg_2: byte
        if(state.fail)
            return state.fail(start0);
        byte arg_2 = state.pickObj();

        state = match(41, state, 3); // arg_3: byte
        if(state.fail)
            return state.fail(start0);
        byte arg_3 = state.pickObj();

        state = match(41, state, 4); // arg_4: byte
        if(state.fail)
            return state.fail(start0);
        byte arg_4 = state.pickObj();

        state = match(41, state, 5); // arg_5: byte
        if(state.fail)
            return state.fail(start0);
        byte arg_5 = state.pickObj();

        int value;
        try{
            value = state.catalog.escU(arg_0, arg_1, arg_2, arg_3, arg_4, arg_5);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // regex rule for: @Ch(except="\\\"",range={32,1114111})int
    static _State rule_37(_State state) throws _FatalEx
    {
        return match_regex_int(state, 37, pattern_37, 0);
    }
    static final java.util.regex.Pattern pattern_37 = java.util.regex.Pattern.compile("[\\ -\\x{10FFFF}&&[^\\\\\"]]", 0);

    // regex rule for: @Ch("\\")Void
    static _State rule_38(_State state)
    {
        return match_regex(state, 38, pattern_38, 0);
    }
    static final java.util.regex.Pattern pattern_38 = java.util.regex.Pattern.compile("\\\\", 0);

    // regex rule for: @Ch("\\\"/bfnrt")char
    static _State rule_39(_State state) throws _FatalEx
    {
        return match_regex_char(state, 39, pattern_39, 0);
    }
    static final java.util.regex.Pattern pattern_39 = java.util.regex.Pattern.compile("[\\\\\"/bfnrt]", 0);

    // regex rule for: @Ch("u")Void
    static _State rule_40(_State state)
    {
        return match_regex(state, 40, pattern_40, 0);
    }
    static final java.util.regex.Pattern pattern_40 = java.util.regex.Pattern.compile("u", 0);

    // concat rule for: byte
    static _State rule_41(_State state) throws _FatalEx
    {
        final int start0 = state.start;

        state = match(42, state, 0); // arg_0: @Regex("[0-9A-Fa-f]")char
        if(state.fail)
            return state.fail(start0);
        char arg_0 = state.pickObj();

        byte value;
        try{
            value = state.catalog.hex(arg_0);
        }catch(Exception ex){
            throw new _FatalEx(start0, ex);
        }
        return state.ok(value);
    }

    // regex rule for: @Regex("[0-9A-Fa-f]")char
    static _State rule_42(_State state) throws _FatalEx
    {
        return match_regex_char(state, 42, pattern_42, 0);
    }
    static final java.util.regex.Pattern pattern_42 = java.util.regex.Pattern.compile("[0-9A-Fa-f]", 0);



    // = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
    //
    // = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

    static _State match_repeat(_State state, int ruleId, int subRuleId, int min, int max) throws _FatalEx
    {
        final int start0 = state.start;
        java.util.ArrayList<Object> list = new java.util.ArrayList<>(Math.max(min, Math.min(10, max)));
        for(int i=0; i<max; i++)
        {
            final int start1 = state.start;
            state = match(subRuleId, state, i);
            if(i<min && state.fail)
                return state.fail(start0);
            if(i>=min && state.fail) // enough elements
                break;
            if(i>=min && start1==state.start) // no progress, enough elements
                break;
            list.add(state.pickObj());
        }
        return state.ok(list);
    }

    static _State match_regex(_State state, int ruleId, java.util.regex.Pattern pattern, int group)
    {
        var matcher = pattern.matcher(state.chars);
        matcher.region(state.start, state.end);
        boolean matched = matcher.lookingAt();
        if(!matched)
            return state.fail(state.start, failReason_regex, null, ruleId, state.start);

        state.gStart = matcher.start(group);
        state.gEnd = matcher.end(group);
        if(state.gStart==-1)
            return state.fail(state.start, failReason_regex_group, null, ruleId, state.start);

        state.start = matcher.end(0); // consume group 0
        return state.ok(null);
    }
    static _State match_regex_char(_State state, int ruleId, java.util.regex.Pattern pattern, int group) throws _FatalEx
    {
        state = match_regex_int(state, ruleId, pattern, group);
        if(state.fail)
            return state;
        Integer x = state.pickObj();
        if(x>0xFFFF)
        {
            // programming mistake in the regex, or an unexpected input
            String msg = "expected to match exactly 1 char; matched=%s, start=%s, end=%s, regex=%s"
                .formatted(Integer.toHexString(x), state.gStart, state.gEnd, pattern.pattern());
            throw new _FatalEx(state.gStart, new Exception(msg));
        }
        return state.ok(Character.valueOf((char)x.intValue()));
    }
    static _State match_regex_int(_State state, int ruleId, java.util.regex.Pattern pattern, int group) throws _FatalEx
    {
        state = match_regex(state, ruleId, pattern, group);
        if(state.fail)
            return state;
        int count = Character.codePointCount(state.chars, state.gStart, state.gEnd);
        if(count==1)
        {
            int code = Character.codePointAt(state.chars, state.gStart);
            if(Character.charCount(code)==state.gEnd-state.gStart) // could it fail?
                return state.ok(code);
        }
        // programming mistake in the regex, or an unexpected input
        String msg = "expected to match exactly 1 code point; start=%s, end=%s, regex=%s"
            .formatted(state.gStart, state.gEnd, pattern.pattern());
        throw new _FatalEx(state.gStart, new Exception(msg));
    }
    static _State match_regex_str(_State state, int ruleId, java.util.regex.Pattern pattern, int group)
    {
        state = match_regex(state, ruleId, pattern, group);
        if(state.fail)
            return state;
        String str = state.chars.subSequence(state.gStart, state.gEnd).toString();
        return state.ok(str);
    }
    static _State match_regex_obj(_State state, int ruleId, java.util.regex.Pattern pattern, int group, Object obj)
    {
        state = match_regex(state, ruleId, pattern, group);
        if(state.fail)
            return state;
        return state.ok(obj);
    }
    static class _DatatypeList
    {
        // [0] Expr
        static org.knime.core.table.virtual.expression.ExpressionGrammar.Expr t_0;
        // [1] Sum
        static org.knime.core.table.virtual.expression.ExpressionGrammar.Sum t_1;
        // [2] SepBy1<Term,@Ch("+-")String>
        static org.rekex.helper.datatype.SepBy1<org.knime.core.table.virtual.expression.ExpressionGrammar.Term,java.lang.@org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value="+-")String> t_2;
        // [3] Term
        static org.knime.core.table.virtual.expression.ExpressionGrammar.Term t_3;
        // [4] List<Seq2<@Ch("+-")String,Term>>
        static java.util.List<org.rekex.helper.datatype.seq.Seq2<java.lang.@org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value="+-")String,org.knime.core.table.virtual.expression.ExpressionGrammar.Term>> t_4;
        // [5] SepBy1<Factor,@Ch("*/%")String>
        static org.rekex.helper.datatype.SepBy1<org.knime.core.table.virtual.expression.ExpressionGrammar.Factor,java.lang.@org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value="*/%")String> t_5;
        // [6] Seq2<@Ch("+-")String,Term>
        static org.rekex.helper.datatype.seq.Seq2<java.lang.@org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value="+-")String,org.knime.core.table.virtual.expression.ExpressionGrammar.Term> t_6;
        // [7] Factor
        static org.knime.core.table.virtual.expression.ExpressionGrammar.Factor t_7;
        // [8] List<Seq2<@Ch("*/%")String,Factor>>
        static java.util.List<org.rekex.helper.datatype.seq.Seq2<java.lang.@org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value="*/%")String,org.knime.core.table.virtual.expression.ExpressionGrammar.Factor>> t_8;
        // [9] @Ch("+-")String
        static java.lang.@org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value="+-")String t_9;
        // [10] Factor
        static org.knime.core.table.virtual.expression.ExpressionGrammar.Factor t_10;
        // [11] Factor
        static org.knime.core.table.virtual.expression.ExpressionGrammar.Factor t_11;
        // [12] Seq2<@Ch("*/%")String,Factor>
        static org.rekex.helper.datatype.seq.Seq2<java.lang.@org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value="*/%")String,org.knime.core.table.virtual.expression.ExpressionGrammar.Factor> t_12;
        // [13] OptWs
        static org.knime.core.table.virtual.expression.ExpressionGrammar.OptWs t_13;
        // [14] Atom
        static org.knime.core.table.virtual.expression.ExpressionGrammar.Atom t_14;
        // [15] @Ch("*/%")String
        static java.lang.@org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value="*/%")String t_15;
        // [16] Atom
        static org.knime.core.table.virtual.expression.ExpressionGrammar.Atom t_16;
        // [17] Atom
        static org.knime.core.table.virtual.expression.ExpressionGrammar.Atom t_17;
        // [18] Atom
        static org.knime.core.table.virtual.expression.ExpressionGrammar.Atom t_18;
        // [19] Atom
        static org.knime.core.table.virtual.expression.ExpressionGrammar.Atom t_19;
        // [20] Atom
        static org.knime.core.table.virtual.expression.ExpressionGrammar.Atom t_20;
        // [21] Atom
        static org.knime.core.table.virtual.expression.ExpressionGrammar.Atom t_21;
        // [22] @Ch("$")Void
        static java.lang.@org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value="$")Void t_22;
        // [23] @Ch("[")Void
        static java.lang.@org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value="[")Void t_23;
        // [24] StrConst
        static org.knime.core.table.virtual.expression.ExpressionGrammar.StrConst t_24;
        // [25] @Ch("]")Void
        static java.lang.@org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value="]")Void t_25;
        // [26] @Regex("[0-9]+")String
        static java.lang.@org.rekex.spec.Regex(flags=0, group=0, value="[0-9]+")String t_26;
        // [27] @Ch(except="\\\" \t\n\r+-*/%",range={32,1114111})int[]
        static @org.rekex.helper.anno.Ch(except="\\\" \t\n\r+-*/%", ignoreCase=false, range={32, 1114111}, value="")int[] t_27;
        // [28] @Ch("(")Void
        static java.lang.@org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value="(")Void t_28;
        // [29] @Ch(")")Void
        static java.lang.@org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value=")")Void t_29;
        // [30] @Ch("\"")Void
        static java.lang.@org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value="\"")Void t_30;
        // [31] int[]
        static int[] t_31;
        // [32] @Ch(except="\\\" \t\n\r+-*/%",range={32,1114111})int
        static @org.rekex.helper.anno.Ch(except="\\\" \t\n\r+-*/%", ignoreCase=false, range={32, 1114111}, value="")int t_32;
        // [33] int
        static int t_33;
        // [34] int
        static int t_34;
        // [35] int
        static int t_35;
        // [36] int
        static int t_36;
        // [37] @Ch(except="\\\"",range={32,1114111})int
        static @org.rekex.helper.anno.Ch(except="\\\"", ignoreCase=false, range={32, 1114111}, value="")int t_37;
        // [38] @Ch("\\")Void
        static java.lang.@org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value="\\")Void t_38;
        // [39] @Ch("\\\"/bfnrt")char
        static @org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value="\\\"/bfnrt")char t_39;
        // [40] @Ch("u")Void
        static java.lang.@org.rekex.helper.anno.Ch(except="", ignoreCase=false, range={}, value="u")Void t_40;
        // [41] byte
        static byte t_41;
        // [42] @Regex("[0-9A-Fa-f]")char
        static @org.rekex.spec.Regex(flags=0, group=0, value="[0-9A-Fa-f]")char t_42;

        static final java.util.ArrayList<org.rekex.annotype.AnnoType> list = new java.util.ArrayList<>();
        static
        {
            for(int id=0; id<43; id++)
            {
                java.lang.reflect.Field field;
                try{ field = _DatatypeList.class.getDeclaredField("t_"+id); }
                catch(Exception ex){ ex.printStackTrace(); throw new Error(ex); }
                var type = org.rekex.annotype.TypeMath.convertFromJlr(field.getAnnotatedType());
                list.add(type);
            }
        }
    }

}
